import 'package:tob/generated/json/base/json_convert_content.dart';
import 'package:tob/generated/json/base/json_field.dart';

class PurchaseFileEntity with JsonConvert<PurchaseFileEntity> {
	int id;
	@JSONField(name: "purchase_id")
	int purchaseId;
	@JSONField(name: "dealer_id")
	int dealerId;
	String vin;
	@JSONField(name: "spec_id")
	int specId;
	@JSONField(name: "color_id")
	int colorId;
	String createtime;
	int updatetime;
	@JSONField(name: "color_name")
	String colorName;
	int state;
	@JSONField(name: "vin_id")
	int vinId;
	@JSONField(name: "client_name")
	String clientName;
	@JSONField(name: "client_mobile")
	String clientMobile;
	@JSONField(name: "client_mobile_state")
	String clientMobileState;
	@JSONField(name: "client_mobile_remarks")
	String clientMobileRemarks;
	@JSONField(name: "license_z_image")
	String licenseZImage;
	@JSONField(name: "license_f_image")
	String licenseFImage;
	@JSONField(name: "license_f_state")
	int licenseFState;
	@JSONField(name: "license_f_remarks")
	String licenseFRemarks;
	@JSONField(name: "cert_image")
	String certImage;
	@JSONField(name: "cert_state")
	String certState;
	@JSONField(name: "cert_remarks")
	String certRemarks;
	@JSONField(name: "invoice_image")
	String invoiceImage;
	@JSONField(name: "invoice_state")
	String invoiceState;
	@JSONField(name: "invoice_remarks")
	String invoiceRemarks;
	@JSONField(name: "client_id_z_image")
	String clientIdZImage;
	@JSONField(name: "client_id_f_image")
	String clientIdFImage;
	@JSONField(name: "client_idcode")
	String clientIdcode;
	@JSONField(name: "certificate_image")
	String certificateImage;
	@JSONField(name: "certificate_image_state")
	String certificateImageState;
	@JSONField(name: "certificate_image_remarks")
	String certificateImageRemarks;
	@JSONField(name: "client_id_z_image_state")
	String clientIdZImageState;
	@JSONField(name: "client_id_z_image_remarks")
	String clientIdZImageRemarks;
	@JSONField(name: "client_id_f_image_state")
	String clientIdFImageState;
	@JSONField(name: "client_id_f_image_remarks")
	String clientIdFImageRemarks;
	int examinetime;
	@JSONField(name: "backmoney_status")
	String backmoneyStatus;
	@JSONField(name: "backmoney_time")
	int backmoneyTime;
	@JSONField(name: "business_image")
	dynamic businessImage;
	@JSONField(name: "business_image_state")
	dynamic businessImageState;
	@JSONField(name: "business_image_remarks")
	dynamic businessImageRemarks;
	@JSONField(name: "business_name")
	dynamic businessName;
	@JSONField(name: "business_mobile")
	dynamic businessMobile;
	@JSONField(name: "business_code")
	dynamic businessCode;
	@JSONField(name: "register_type")
	dynamic registerType;
}
